# Generated by Django 2.0.4 on 2018-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('userid', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_zt', models.CharField(max_length=200)),
                ('pl_bt', models.CharField(max_length=200)),
                ('pl_name', models.CharField(max_length=200)),
                ('con', models.CharField(max_length=10000)),
                ('pl_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wz_name', models.CharField(max_length=500)),
                ('wz_zzjy', models.CharField(max_length=1000)),
                ('wz_nr', models.TextField(max_length=10000)),
                ('wz_time', models.CharField(max_length=20)),
                ('wz_zz', models.CharField(max_length=20)),
                ('wz_dz', models.IntegerField()),
                ('wz_lll', models.IntegerField()),
                ('wz_by1', models.CharField(max_length=1000)),
                ('wz_by2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
